### ISSUE TITLE
ViaVersion

### ISSUE THREAD

**Issue by RoottheAdmin** [Xernium/ProtocolSupport-Bedrock-Dev#46]
Can you add ViaVersion support to this version (plz keep on 1.13.2 for that update)

**Comment by Xernium** [comment]
@RoottheAdmin it does support ViaVersion. You just have to use a Paper server, if you do it will just work like magic together. If you can’t then there is no way to do it.

**Comment by RoottheAdmin** [comment]
So if I use paper then i will be able to use viaversion?

**Comment by Xernium** [comment]
That is precisely what I said...
